<h1>Créditos</h1>
<article>
    <header>
        <h2>Patrocinadores</h2>
    </header>
    <section>
        <ul>
            <li>
                <p>Other Selves es una editorial pequeña que publica con mucho mimo los juegos de rol que les apasionan.</p>
                <a href="//other-selves.com" target="_blank"><img alt="Logo de Other Selves" height="84px" loading="lazy" src="/img/logos/other_selves/logo.svg"></a>
            </li>
            <li>
                <p>Raquel y Alfredo llevan 19 años haciendo comunidad con su web RolGratis.com y su presencia en jornadas.</p>
                <a href="//rolgratis.com" target="_blank"><img alt="Logo de Rol Gratis" height="126px" loading="lazy" src="/img/logos/rol_gratis/logo.svg"></a>
            </li>
            <li>
                <p>En 77MUNDOS publican desde ciencia ficción hasta fantasía y su comunidad crece con cada mecenazgo.</p>
                <a href="//77mundos.es" target="_blank"><img alt="Logo de 77 Mundos" height="105px" loading="lazy" src="/img/logos/77_mundos/logo.svg"></a>
            </li>
            <li>
                <p>Distribuciones Sombra lleva los juegos de rol a las tiendas desde finales de los '90.</p>
                <a href="//edsombra.com" target="_blank"><img alt="Logo de Distribuciones Sombra" height="63px" loading="lazy" src="/img/logos/sombra/logo.svg"></a>
            </li>
            <li>
                <p>Las jornadas RunasNet han logrado crear una sólida comunidad de aficionados a los juegos de rol d100.</p>
                <a href="//runasnet.org" target="_blank"><img alt="Logo de las Runas NET" height="126px" loading="lazy" src="/img/logos/runas_net/logo.svg"></a>
            </li>
        </ul>
    </section>
</article>

<article>
    <header>
        <h2>Recursos</h2>
    </header>
    <section>
        <ul>
            <li>
                <p>Los cimientos de R+, para que navegues más rápido y seguro.</p>
                <a href="//kumbiaphp.com" target="_blank"><img alt="Logo de KumbiaPHP" height="42px" loading="lazy" src="/img/logos/kumbiaphp.svg"></a>
            </li>
            <li>
                <p>El aspecto visual de R+4, para alegrarte la vista.</p>
                <a href="//kumbiacss.com" target="_blank"><img alt="Logo de KumbiaPHP" height="42px" loading="lazy" src="/img/logos/kumbiacss.svg"></a>
            </li>
            <li>
                <p>Las tipografías Norse y Troika de Joel, para que flipes.</p>
                <a href="//joelcarrouche.com" target="_blank"><?=_img::icon('md/link')?></a>
            </li>
            <li>
                <p>La tipografía de dados que usamos en R+3, para que sigas flipando. “GamingDice” font © 2013 Joshua Dale Meadows and released under Creative Commons Attributions CC BY License.</p>
                <a href="//drivethrurpg.com/en/product/120722" target="_blank"><?=_img::icon('md/link')?></a>
            </li>
            <li>
                <p>El logo que hizo Flor Benitez Piceda (Pinceladas de Plata) para R+3, un grimorio.</p>
                <a href="//www.youtube.com/@Pinceladasdeplata" target="_blank"><?=_img::icon('md/link')?></a>
            </li>
            <li>
                <p>Para generar los favicon correctos.</p>
                <a href="//realfavicongenerator.net" target="_blank"><?=_img::icon('md/link')?></a>
            </li>
            <li>
                <p>Para reducir el peso de las tipografías TTF y OTF.</p>
                <a href="//cloudconvert.com" target="_blank"><?=_img::icon('md/link')?></a>
            </li>
        </ul>
    </section>
</article>
